FROM node:20-alpine AS base

FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
WORKDIR /app
ARG NEXT_PUBLIC_QA_MODE=false
ENV NEXT_PUBLIC_QA_MODE=$NEXT_PUBLIC_QA_MODE
ARG NEXT_PUBLIC_EXAM_DURATION_SECONDS=960
ENV NEXT_PUBLIC_EXAM_DURATION_SECONDS=$NEXT_PUBLIC_EXAM_DURATION_SECONDS
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 8080
CMD ["node", "server.js"]
